$provision = <<SCRIPT
  yum -y remove epel-release
  rpm -Uvh "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
  yum -y install tmux
SCRIPT

$run_always = <<SCRIPT
  tmux new-session -d -s rocks 'insert-ethers'
  tmux send-keys -t rocks Enter
SCRIPT

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.ssh.pty = true
  config.vm.define "master" do |master|
    master.vm.box = "sridhav/rocks"
    master.vm.network "private_network", ip: "192.168.60.20", virtualbox__intnet: "rocks_internal"
    config.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.cpus = "1"
      v.memory = "4096"
    end
  end
  config.vm.provision "shell", inline: $provision
  config.vm.provision "shell", inline: $run_always, run: 'always'
end


