$build = <<SCRIPT
  yum -y update
  yum -y install wget
  mkdir /tmp/mpich
  cd /opt/ && wget http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz
  tar -xvzf mpich-3.2.tar.gz
  cd /tmp/mpich && /opt/mpich-3.2/configure --prefix=/opt/mpich --disable-fortran --disable-cxx
  make
  make install
  ssh-keygen -b 4096 -t rsa -f /opt/ssh_keys/id_rsa -q -N ""
  mv /opt/ssh_keys/id_rsa /home/vagrant/.ssh/id_rsa
SCRIPT

$client = <<SCRIPT
  echo "export PATH=/opt/mpich/bin:$PATH" >> /home/vagrant/.bash_profile
  cat /opt/ssh_keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  chown -R vagrant /home/vagrant
SCRIPT

$hwloc_install = <<SCRIPT
  yum -y install wget
  mkdir -p /opt/torque/hwloc_install && cd /opt/torque
  wget https://www.open-mpi.org/software/hwloc/v1.9/downloads/hwloc-1.9.1.tar.gz
  tar -xvzf hwloc-1.9.1.tar.gz
  cd hwloc-1.9.1
  ./configure --prefix=/opt/torque/hwloc_install
  make install
SCRIPT

$torque_server = <<SCRIPT
  echo /opt/torque/hwloc_install/lib/ >/etc/ld.so.conf.d/hwloc.conf
  ldconfig
SCRIPT

$torque_install = <<SCRIPT
  yum -y install libtool openssl-devel libxml2-devel boost-devel gcc gcc-c++
  mkdir -p /opt/torque/torque_install && cd /opt/torque
  wget http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
  tar -xvzf torque-6.1.0.tar.gz
  cd torque-6.1.0
  ./configure --prefix=/opt/torque/torque_install --enable-cgroups --with-hwloc-path=/opt/torque/hwloc_install
  make install
  make packages
  mkdir -p /opt/torque/torque_clients
  mv torque-package-*.sh /opt/torque/torque_clients/ 
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "mpi_install", "/opt/mpich"
  config.vm.synced_folder "hwloc_install", "/opt/torque/hwloc_install"
  config.vm.synced_folder "torque_install", "/opt/torque/torque_install"
  config.vm.synced_folder "torque_packages", "/opt/torque/torque_clients"
  config.vm.synced_folder "keys", "/opt/ssh_keys"
  config.vm.synced_folder "scripts", "/opt/scripts"
  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "1024"
    end
    master.vm.provision "shell", inline: $hwloc_install
    master.vm.provision "shell", inline: $torque_install
  end

  # (1..2).each do |i|
  #   config.vm.define "node-#{i}" do |node|
  #     node.vm.hostname = "node-#{i}"
  #     node.vm.provision "shell", inline: $client
  #     node.vm.network "private_network", ip: "192.168.33.1#{i}"
  #     node.vm.provider "virtualbox" do |vb|
  #       vb.cpus = 1
  #       vb.memory = "1024"
  #     end
  #   end
  # end
end
